
[GOOGLE]
location_max_distance = 3                 # Use: 0 = 2km, 1 = 10km, 2 = 25km, 3 = 50km, 4 = 100km, 5 = 300km, 6 = Anywhere
max_date_posted = 3                       # Use: 0 = All, 1 = Past day, 2 = Past 3 days, 3 = Past week, 4 = Past month
